### ISSUE TITLE
clear-field button customization 

### ISSUE THREAD

**Issue by mrlobatoman** [Espressogoddess/whats-cookin#45]
When a user types text into the input field, a dark blue "x" button appears on the right side.
The contrast is poor and not as user accessible as it should be. 
- To target the specific element, I had to go to my Dev Tools settings and click "show user agent Shadow DOM"
- From there, using the inspector tools, you can single out the small field for the clear field button. 
- I've tried to manipulate the properties of the button but it doesn't seem to do anything. 
- Here is the code block that pops up in Dev Tools:
 
           input[type="search" i]::-webkit-search-cancel-button {
                appearance: auto;
                display: block;
                cursor: default;
                margin-inline-start: 1px;
                margin-right: 3px;
                opacity: 0;
                pointer-events: none;
                -webkit-user-modify: read-only !important;
                user-select: none !important;
                flex: 0 0 auto;
            }

**Comment by espressoGoddess** [comment]
I don't think that this is something that we should worry about tbh, shadow DOM, as you know, is incredibly tricky to target and change.
