### ISSUE TITLE
Fetch with page load 

### ISSUE THREAD

**Issue by SamanthaMcElhinney** [Espressogoddess/whats-cookin#46]
- Currently our entire application is wrapped in our `loadPage` function. We need to refactor for only including functions necessary on page load for data from fetch. 
- It may be beneficial when we refactor to use apiCalls.js for POST and FETCH. 
- We also need to refactor for locally scoped verse globally scoped variables.

**Comment by Espressogoddess** [comment]
I deglobalized variables wherever I could
After talking with Cass, it doesn't sound like it matters for us to utilize the apiCalls.js file

**Comment by espressoGoddess** [comment]
I deglobalized variables wherever I could
After talking with Cass, it doesn't sound like it matters for us to utilize the apiCalls.js file
I got rid of the load page function!!
